// ISO 3166-1 numeric → alpha-2 mapping. world-atlas TopoJSON uses numeric
// country codes as feature ids; our backend (db-ip / MaxMind) emits alpha-2.
// Source: ISO 3166-1 standard (2024).

export const numericToAlpha2: Record<string, string> = {
  "004": "AF", "008": "AL", "010": "AQ", "012": "DZ", "016": "AS", "020": "AD",
  "024": "AO", "028": "AG", "031": "AZ", "032": "AR", "036": "AU", "040": "AT",
  "044": "BS", "048": "BH", "050": "BD", "051": "AM", "052": "BB", "056": "BE",
  "060": "BM", "064": "BT", "068": "BO", "070": "BA", "072": "BW", "074": "BV",
  "076": "BR", "084": "BZ", "086": "IO", "090": "SB", "092": "VG", "096": "BN",
  "100": "BG", "104": "MM", "108": "BI", "112": "BY", "116": "KH", "120": "CM",
  "124": "CA", "132": "CV", "136": "KY", "140": "CF", "144": "LK", "148": "TD",
  "152": "CL", "156": "CN", "158": "TW", "162": "CX", "166": "CC", "170": "CO",
  "174": "KM", "175": "YT", "178": "CG", "180": "CD", "184": "CK", "188": "CR",
  "191": "HR", "192": "CU", "196": "CY", "203": "CZ", "204": "BJ", "208": "DK",
  "212": "DM", "214": "DO", "218": "EC", "222": "SV", "226": "GQ", "231": "ET",
  "232": "ER", "233": "EE", "234": "FO", "238": "FK", "239": "GS", "242": "FJ",
  "246": "FI", "248": "AX", "250": "FR", "254": "GF", "258": "PF", "260": "TF",
  "262": "DJ", "266": "GA", "268": "GE", "270": "GM", "275": "PS", "276": "DE",
  "288": "GH", "292": "GI", "296": "KI", "300": "GR", "304": "GL", "308": "GD",
  "312": "GP", "316": "GU", "320": "GT", "324": "GN", "328": "GY", "332": "HT",
  "334": "HM", "336": "VA", "340": "HN", "344": "HK", "348": "HU", "352": "IS",
  "356": "IN", "360": "ID", "364": "IR", "368": "IQ", "372": "IE", "376": "IL",
  "380": "IT", "384": "CI", "388": "JM", "392": "JP", "398": "KZ", "400": "JO",
  "404": "KE", "408": "KP", "410": "KR", "414": "KW", "417": "KG", "418": "LA",
  "422": "LB", "426": "LS", "428": "LV", "430": "LR", "434": "LY", "438": "LI",
  "440": "LT", "442": "LU", "446": "MO", "450": "MG", "454": "MW", "458": "MY",
  "462": "MV", "466": "ML", "470": "MT", "474": "MQ", "478": "MR", "480": "MU",
  "484": "MX", "492": "MC", "496": "MN", "498": "MD", "499": "ME", "500": "MS",
  "504": "MA", "508": "MZ", "512": "OM", "516": "NA", "520": "NR", "524": "NP",
  "528": "NL", "531": "CW", "533": "AW", "534": "SX", "535": "BQ", "540": "NC",
  "548": "VU", "554": "NZ", "558": "NI", "562": "NE", "566": "NG", "570": "NU",
  "574": "NF", "578": "NO", "580": "MP", "581": "UM", "583": "FM", "584": "MH",
  "585": "PW", "586": "PK", "591": "PA", "598": "PG", "600": "PY", "604": "PE",
  "608": "PH", "612": "PN", "616": "PL", "620": "PT", "624": "GW", "626": "TL",
  "630": "PR", "634": "QA", "638": "RE", "642": "RO", "643": "RU", "646": "RW",
  "652": "BL", "654": "SH", "659": "KN", "660": "AI", "662": "LC", "663": "MF",
  "666": "PM", "670": "VC", "674": "SM", "678": "ST", "682": "SA", "686": "SN",
  "688": "RS", "690": "SC", "694": "SL", "702": "SG", "703": "SK", "704": "VN",
  "705": "SI", "706": "SO", "710": "ZA", "716": "ZW", "724": "ES", "728": "SS",
  "729": "SD", "732": "EH", "740": "SR", "744": "SJ", "748": "SZ", "752": "SE",
  "756": "CH", "760": "SY", "762": "TJ", "764": "TH", "768": "TG", "772": "TK",
  "776": "TO", "780": "TT", "784": "AE", "788": "TN", "792": "TR", "795": "TM",
  "796": "TC", "798": "TV", "800": "UG", "804": "UA", "807": "MK", "818": "EG",
  "826": "GB", "831": "GG", "832": "JE", "833": "IM", "834": "TZ", "840": "US",
  "850": "VI", "854": "BF", "858": "UY", "860": "UZ", "862": "VE", "876": "WF",
  "882": "WS", "887": "YE", "894": "ZM",
};

export const alpha2ToName: Record<string, string> = {
  AF: "Afghanistan", AL: "Albania", AQ: "Antarctica", DZ: "Algeria", AS: "American Samoa",
  AD: "Andorra", AO: "Angola", AG: "Antigua and Barbuda", AZ: "Azerbaijan", AR: "Argentina",
  AU: "Australia", AT: "Austria", BS: "Bahamas", BH: "Bahrain", BD: "Bangladesh",
  AM: "Armenia", BB: "Barbados", BE: "Belgium", BM: "Bermuda", BT: "Bhutan",
  BO: "Bolivia", BA: "Bosnia and Herzegovina", BW: "Botswana", BR: "Brazil",
  BZ: "Belize", IO: "British Indian Ocean Territory", SB: "Solomon Islands",
  VG: "British Virgin Islands", BN: "Brunei", BG: "Bulgaria", MM: "Myanmar",
  BI: "Burundi", BY: "Belarus", KH: "Cambodia", CM: "Cameroon", CA: "Canada",
  CV: "Cape Verde", KY: "Cayman Islands", CF: "Central African Republic",
  LK: "Sri Lanka", TD: "Chad", CL: "Chile", CN: "China", TW: "Taiwan",
  CX: "Christmas Island", CC: "Cocos Islands", CO: "Colombia", KM: "Comoros",
  CG: "Congo", CD: "DR Congo", CK: "Cook Islands", CR: "Costa Rica",
  HR: "Croatia", CU: "Cuba", CY: "Cyprus", CZ: "Czech Republic", BJ: "Benin",
  DK: "Denmark", DM: "Dominica", DO: "Dominican Republic", EC: "Ecuador",
  SV: "El Salvador", GQ: "Equatorial Guinea", ET: "Ethiopia", ER: "Eritrea",
  EE: "Estonia", FO: "Faroe Islands", FK: "Falkland Islands",
  GS: "South Georgia", FJ: "Fiji", FI: "Finland", AX: "Åland Islands",
  FR: "France", GF: "French Guiana", PF: "French Polynesia",
  TF: "French Southern Territories", DJ: "Djibouti", GA: "Gabon",
  GE: "Georgia", GM: "Gambia", PS: "Palestine", DE: "Germany",
  GH: "Ghana", GI: "Gibraltar", KI: "Kiribati", GR: "Greece",
  GL: "Greenland", GD: "Grenada", GP: "Guadeloupe", GU: "Guam",
  GT: "Guatemala", GN: "Guinea", GY: "Guyana", HT: "Haiti",
  VA: "Vatican City", HN: "Honduras", HK: "Hong Kong", HU: "Hungary",
  IS: "Iceland", IN: "India", ID: "Indonesia", IR: "Iran", IQ: "Iraq",
  IE: "Ireland", IL: "Israel", IT: "Italy", CI: "Ivory Coast",
  JM: "Jamaica", JP: "Japan", KZ: "Kazakhstan", JO: "Jordan",
  KE: "Kenya", KP: "North Korea", KR: "South Korea", KW: "Kuwait",
  KG: "Kyrgyzstan", LA: "Laos", LB: "Lebanon", LS: "Lesotho",
  LV: "Latvia", LR: "Liberia", LY: "Libya", LI: "Liechtenstein",
  LT: "Lithuania", LU: "Luxembourg", MO: "Macao", MG: "Madagascar",
  MW: "Malawi", MY: "Malaysia", MV: "Maldives", ML: "Mali",
  MT: "Malta", MQ: "Martinique", MR: "Mauritania", MU: "Mauritius",
  MX: "Mexico", MC: "Monaco", MN: "Mongolia", MD: "Moldova",
  ME: "Montenegro", MS: "Montserrat", MA: "Morocco", MZ: "Mozambique",
  OM: "Oman", NA: "Namibia", NR: "Nauru", NP: "Nepal", NL: "Netherlands",
  CW: "Curaçao", AW: "Aruba", SX: "Sint Maarten", BQ: "Caribbean Netherlands",
  NC: "New Caledonia", VU: "Vanuatu", NZ: "New Zealand", NI: "Nicaragua",
  NE: "Niger", NG: "Nigeria", NU: "Niue", NF: "Norfolk Island",
  NO: "Norway", MP: "Northern Mariana Islands", UM: "U.S. Minor Outlying Islands",
  FM: "Micronesia", MH: "Marshall Islands", PW: "Palau", PK: "Pakistan",
  PA: "Panama", PG: "Papua New Guinea", PY: "Paraguay", PE: "Peru",
  PH: "Philippines", PN: "Pitcairn", PL: "Poland", PT: "Portugal",
  GW: "Guinea-Bissau", TL: "Timor-Leste", PR: "Puerto Rico", QA: "Qatar",
  RE: "Réunion", RO: "Romania", RU: "Russia", RW: "Rwanda",
  BL: "Saint Barthélemy", SH: "Saint Helena", KN: "Saint Kitts and Nevis",
  AI: "Anguilla", LC: "Saint Lucia", MF: "Saint Martin", PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent", SM: "San Marino", ST: "São Tomé and Príncipe",
  SA: "Saudi Arabia", SN: "Senegal", RS: "Serbia", SC: "Seychelles",
  SL: "Sierra Leone", SG: "Singapore", SK: "Slovakia", VN: "Vietnam",
  SI: "Slovenia", SO: "Somalia", ZA: "South Africa", ZW: "Zimbabwe",
  ES: "Spain", SS: "South Sudan", SD: "Sudan", EH: "Western Sahara",
  SR: "Suriname", SJ: "Svalbard and Jan Mayen", SZ: "Eswatini", SE: "Sweden",
  CH: "Switzerland", SY: "Syria", TJ: "Tajikistan", TH: "Thailand",
  TG: "Togo", TK: "Tokelau", TO: "Tonga", TT: "Trinidad and Tobago",
  AE: "United Arab Emirates", TN: "Tunisia", TR: "Turkey", TM: "Turkmenistan",
  TC: "Turks and Caicos Islands", TV: "Tuvalu", UG: "Uganda", UA: "Ukraine",
  MK: "North Macedonia", EG: "Egypt", GB: "United Kingdom", GG: "Guernsey",
  JE: "Jersey", IM: "Isle of Man", TZ: "Tanzania", US: "United States",
  VI: "U.S. Virgin Islands", BF: "Burkina Faso", UY: "Uruguay", UZ: "Uzbekistan",
  VE: "Venezuela", WF: "Wallis and Futuna", WS: "Samoa", YE: "Yemen", ZM: "Zambia",
};

export function countryName(code: string): string {
  if (code === "??") return "Unknown";
  return alpha2ToName[code] ?? code;
}

export function flagEmoji(code: string): string {
  if (!code || code.length !== 2 || code === "??") return "🏳️";
  const A = 0x1f1e6;
  const a = "A".charCodeAt(0);
  return (
    String.fromCodePoint(A + code.charCodeAt(0) - a) +
    String.fromCodePoint(A + code.charCodeAt(1) - a)
  );
}
