apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-redirector
  namespace: url-redirector
  labels:
    app: url-redirector
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: url-redirector
  template:
    metadata:
      labels:
        app: url-redirector
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: redirector
          image: ghcr.io/hagi0929/url-redirector:latest
          imagePullPolicy: IfNotPresent
          ports:
            - { name: public, containerPort: 8080 }
            - { name: admin,  containerPort: 8081 }
          livenessProbe:
            httpGet: { path: /healthz, port: public }
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet: { path: /healthz, port: public }
            initialDelaySeconds: 2
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 200m, memory: 128Mi }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          volumeMounts:
            - { name: data, mountPath: /data }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: url-redirector-data
