apiVersion: v1
kind: Service
metadata:
  name: url-redirector
  namespace: url-redirector
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "redirect"
spec:
  type: ClusterIP
  selector: { app: url-redirector }
  ports:
    - { name: public, port: 80, targetPort: public }
---
apiVersion: v1
kind: Service
metadata:
  name: url-redirector-admin
  namespace: url-redirector
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "redirect-admin"
spec:
  type: ClusterIP
  selector: { app: url-redirector }
  ports:
    - { name: admin, port: 80, targetPort: admin }
